### ISSUE TITLE
How to install the React Scaffold

### ISSUE THREAD

**Issue by balduinofernando** [laravel/jetstream#116]
As far as I can see the inertia option at laravel new project comes out with vuejs.
How can I install the ReactJS Scaffold with Laravel Jetstream?

**Comment by lostdesign** [comment]
Jetstream currently only supports Vue as you've seen - if you want react support, you'd need to fork the project and replace the Vue parts with React. Just check this package codebase on how to do that.

**Comment by samraskul** [comment]
Laravel disappoint me, Reactjs is more famous than Vuejs

**Comment by lostdesign** [comment]
Oh no such disappointment..... ![image](https://user-images.githubusercontent.com/5164617/97888505-7e052e00-1d2b-11eb-9ead-099ec0b0d89c.png)

Do yourself a favor and watch this: https://www.youtube.com/watch?v=krn39HjxPTs But since you won't watch it probably, assuming you also didn't follow the discussions about this in general, here is a TLDR just for you:

**Taylor and the team simply don't use react, so why should they maintain something, for free which they don't even use themselves? On top of already maintaining laravel and the other parts of the ecosystem?**

If React is so much better, why does the react community not step in and simply fork the project and replace the vue parts then? What stops you from doing so? You can also just use [fortify-ui](https://github.com/zacksmash/fortify-ui) and write the UI parts yourself.

_I am disappointed in the dudes-wanting-react-in-jetstream-community that cannot even help themselves._
