### ISSUE TITLE
Doesn't work with Laravel 9.35 Model::preventsAccessingMissingAttributes()

### ISSUE THREAD

**Issue by nikosid** [laravel/jetstream#1164]
- Jetstream Version: 2.x-dev
- Jetstream Stack: Livewire
- Uses Teams: yes
- Laravel Version: 9.36.3
- PHP Version: 8.1.10
- Database Driver & Version: MySQL

### Description:

Errors regarding teams when running tests. For example: 

>   The attribute [current_team_id] either does not exist or was not retrieved for model [App\Models\User].

or

>   The attribute [profile_photo_path] either does not exist or was not retrieved for model [App\Models\User].

### Steps To Reproduce:

`sail bin pest --filter "test_confirm_password_screen_can_be_rendered"`

**Comment by markjaquith** [comment]
Confirmed with Laravel 9.36.4 and Jetstream 2.12.3 on a brand new install.

I haven't had time to fully investigate, but this seems to be related to `Auth::user()` returning an object without all the columns.

**Comment by flick36** [comment]
I don't think it's a bug, you have to add what you need to the UserFactory,
 ``` php
'current_team_id' => null,
'profile_photo_path' => null,
'two_factor_secret' => null,
```
 https://github.com/laravel/jetstream/pull/1162#issuecomment-1279309999

**Comment by markjaquith** [comment]
@flick36 But... the UserFactory is created by Jetstream. Shouldn't the user factory it creates work with the tests it creates, while using this new mode that people are (rightly) being encouraged to use? Really asking... maybe the answer is "no", in which case this can be solved by documentation. But making the user factory definition work with these tests in strict mode seems like a kindness that people would appreciate.

**Comment by flick36** [comment]
It adds everything it needs by default, it's up to you to update it based on your needs, not everyone needs teams, twofactor auth, or profile photos, that's why i think it isn't included, and you must activate thos features manually, by uncommenting the corresponding feature on `config/jetstream.php`, so if you need any of those, and YOU want to activate the strict mode, you have to add it to a service provider, you have to then add that to the UserFactory

**Comment by markjaquith** [comment]
Adding these to the user factory definition allows the tests to pass:

```php
 'current_team_id' => null,
'profile_photo_path' => null,
'two_factor_secret' => null,
'two_factor_confirmed_at' => null,
'two_factor_recovery_codes' => null,
```

**Comment by markjaquith** [comment]
> not everyone needs teams, twofactor auth, or profile photos, that's why i think it isn't included, and you must activate thos features manually

I haven't activated these features. The only thing I did after a bog-standard Laravel and Jetstream (Livewire) install was add the one line to activate strict mode.

Further, the migrations to create the columns for these features are created by Jetstream regardless, so it seems reasonable to have the default user factory include defaults for these columns, even if you're not using the underlying features that they power.

If someone not using these features calls `User::first()`, they're going to get an object with these columns included. I think the factory should do the same. What's the downside?

**Comment by citricguy** [comment]
I believe this could also be fixed in the tests themselves.

Adding `$user->refresh();` after the user model is created will refresh the user model with the necessary fields and allow the tests to pass. I think this ensures `Model::preventAccessingMissingAttributes();` is doing what it is supposed to. 

@markjaquith Your factory additions solve this issue as well, but could allow `Model::preventAccessingMissingAttributes();` issues to sneak through tests.
