### ISSUE TITLE
Props not being recognized on render on Profile/Show Vue

### ISSUE THREAD

**Issue by MazeWebArchitect** [laravel/jetstream#1205]
- Jetstream Version: 2.13.1
- Jetstream Stack: Inertia 
- Uses Teams: yes 
- Laravel Version: 9.45.1
- PHP Version: 8.1.13
- Database Driver & Version: MySQL/Mariadb 10.4.27-MariaDB-1:10.4.27+maria~ubu2004

### Description:

Jetstream Props not being recognized on render on Profile/Show Vue using `App\Providers\JetstreamServiceProvider` class. As per https://jetstream.laravel.com/1.x/stacks/inertia.html#customizing-jetstream-s-page-rendering
Although the prop does show up in the Vue Console, it ca not be accessed.

#### Clean Install of Laravel, Intertia an JetStream

1. App\Providers\JetstreamServiceProvider
```
Jetstream::inertia()->whenRendering(
            'Profile/Show',
            function (Request $request, array $data) {
                $test = ['AAA', 'BBB'];
                return array_merge($data, [
                    'test' => $test
                ]);
            }
        );
```

2. UpdateProfileInformationForm.vue
```
<script>
    export default defineComponent({
        props: {
            user: {
                type: Object,
                required: true
            },
            test: {
                type: Array,
                required: true
            }
        },
        created() {
            console.log(this.test)
        },
        data() {
            return {
                form: this.$inertia.form({
                    _method: 'PUT',
                    name: this.user.name,
                    email: this.user.email,
                    test: this.test,
                    photo: null,
                }),

                photoPreview: null,
            }
        }
</script>
```

3. Open up Vue Console after render of /user/profile
Observe the Warning: app.js:13549 [Vue warn]: Missing required prop: "test".

**Comment by jessarcher** [comment]
In your example, the `test` prop is being accessed on the `UpdateProfileInformationForm.vue` component instead of the `Profile/Show.vue` page component that is being passed the prop. Additionally, the example is not using the `<script setup>` syntax and Vue composition API currently shipped with Jetstream, so it's not a minimal reproduction.

If you can confirm the issue exists with the `Profile/Show.vue` component and the `<script setup>` syntax shipped with Jetstream, then please feel free to re-submit the issue.

Otherwise, can you first please try one of the support channels below?

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
