### ISSUE TITLE
Cannot remove pending invitation. Js error

### ISSUE THREAD

**Issue by SachinGanesh** [laravel/jetstream#1233]
- Jetstream Version: v2.14.0
- Jetstream Stack:  Livewire
- Uses Teams: yes
- Laravel Version: v9.46.0
- PHP Version: v8.1.13
- Database Driver & Version: pgsql, 

### Description:
Not able to remove a user from pending invite list. Getting error
```
Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at Directive.value (wire-directives.js:93:24)
    at Directive.get (wire-directives.js:58:33)
    at node_initializer.js:209:42
    at Component.value (index.js:582:9)
    at HTMLButtonElement.<anonymous> (node_initializer.js:201:23)
``` 
![Screenshot 2023-01-25 at 8 06 53 PM](https://user-images.githubusercontent.com/11994640/214592613-d9a3e66a-07f5-4aad-95cd-7dac862a6c2c.png)

**Comment by jessarcher** [comment]
Hi @SachinGanesh,

I'm unable to replicate this on a fresh install of Jetstream 2.16.0 with Livewire and teams enabled.

![Peek 2023-01-27 15-28](https://user-images.githubusercontent.com/4977161/215016342-1d00cd8b-8edd-4ef1-be9d-df8c1fb8909f.gif)

If you can provide instructions on replicating this on a fresh install please feel free to re-open the issue. Otherwise, I'd suggest trying one of the support channels below:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
