### ISSUE TITLE
Vite hot refresh stop working suddenly

### ISSUE THREAD

**Issue by jackdaniel8** [laravel/jetstream#1333]
### Jetstream Version

2.16

### Jetstream Stack

Inertia

### Laravel Version

9.19

### PHP Version

8.0.2

### Database Driver & Version

MYSQL

### Description

Hello, this is the second time this has happened.

For some .vue the hot refresh on save works, but for other .vue nothing happens. We have to do a npm run dev again to see the changes. After working this morning, the refresh on save stop working. I reset everything, nothing. The first time, the problem went away after a while.

Has anyone ever had the same problem?

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';
import i18n from 'laravel-vue-i18n/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.js',
            ssr: 'resources/js/ssr.js',
            refresh: true
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false
                },
            },
        }),
        i18n(),
    ]
});

```

### Steps To Reproduce

-

**Comment by driesvints** [comment]
Thanks. Since we only received this one issue I doubt it's a widespread issue. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
