### ISSUE TITLE
Not possible to have a page with a path /maintenance?

### ISSUE THREAD

**Issue by AdrianwithaW** [laravel/jetstream#1359]
### Jetstream Version

2.16.2

### Jetstream Stack

Inertia

### Laravel Version

9.52.2

### PHP Version

8.1.4

### Database Driver & Version

MySQL 8

### Description

Have built a light CMS using Jetstream for a few small clients I have and one of them has created a page with the slug `/maintenance` for the page path. The page throws a 404 when you try to navigate to the page from a Jetstream link, but will load fine if I load the URL directly. I can't seem to find any other reason why it might do so. As soon as I change the path e.g. to `/maintain` it works fine.

It's probably not that big a deal to change the URL path, but trying to find out if anybody has the same behaviour as a bit of googling doesn't seem to reveal an issue before.

### Steps To Reproduce

1. Create a new Laravel Jetstream set up.
2. Create a route with the url {domain}/maintenance.
3. Navigate to the URL via a `<Link />` component.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

Unfortunately we don't support this version of the library anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
