### ISSUE TITLE
Banner Alerts (BadMethodCallException)

### ISSUE THREAD

**Issue by maikeruit** [laravel/jetstream#1409]
### Jetstream Version

4.1.0

### Jetstream Stack

Livewire

### Laravel Version

10.30.1

### PHP Version

8.2.12

### Description

The documentation says

`return redirect()->route('subscriptions')->banner('Subscription created successfully.');`

But I'm getting an error

> Method Livewire\Features\SupportRedirects\Redirector::banner does not exist.

You may have forgotten to specify the trait `InteractsWithBanner`

### Steps To Reproduce

```
<?php

namespace App\Livewire;

use Livewire\Component;

class ExampleComponent extends Component
{
    public function action()
    {
        return redirect()->route('dashboard')->banner('Subscription created successfully.');
    }
}

```

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
