### ISSUE TITLE
Do you support laravel11? why something went wrong

### ISSUE THREAD

**Issue by phpmac** [laravel/jetstream#1456]
### Jetstream Version

5

### Jetstream Stack

Inertia

### Laravel Version

11

### PHP Version

8.3

### Description

```
   INFO  Middleware [app/Http/Middleware/HandleInertiaRequests.php] created successfully.  

```

当运行 `php artisan jetstream:install inertia` 命令的时候会提示上面这个错误，实际上laravel11路由已经不是那样修改的。   

### Steps To Reproduce

```
   INFO  Middleware [app/Http/Middleware/HandleInertiaRequests.php] created successfully.  

```

当运行 `php artisan jetstream:install inertia` 命令的时候会提示上面这个错误，实际上laravel11路由已经不是那样修改的。

**Comment by jessarcher** [comment]
Hey @phpmac,

I'm not sure from your description what the problem is, but Jetstream does support Laravel 11.

There is a current known bug (#1454) that you may be experiencing, and a PR (https://github.com/laravel/framework/pull/50665) awaiting release to fix it. I've included a temporary workaround at https://github.com/laravel/jetstream/issues/1454#issuecomment-2006066983 that will help if you are experiencing the same issue.

If you're experiencing a different issue, please provide the error message you're getting.

Thanks.
