### ISSUE TITLE
No Session table in Laravel 11. 

### ISSUE THREAD

**Issue by regrub** [laravel/jetstream#1537]
### Jetstream Version

5.x

### Jetstream Stack

Livewire

### Laravel Version

11.23.5

### PHP Version

8.2.20 

### Database Driver & Version

MySQL 8.0 Mamp Pro 7

### Description

When making a new installation in Laravel 11.x and installing Jetstream/Livewire there is no migration file for sessions. This results in an error:

SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select * from `sessions` where `id` = HAyagkD0MNa5HISU7HhrsBqutEHYPcNs6Sc3FuUa limit 1)

### Steps To Reproduce

Follow all the steps on the Laravel site for installing Laravel
Follow all the steps on the Jetstream page for installing Jetstream/Liverwire
DB_CONNECTION=mysql (and other relevant DB_params)
php artisan migrate:fresh

**Comment by regrub** [comment]
Failure in the creation of the database...

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
