### ISSUE TITLE
Installation command fails silently. 

### ISSUE THREAD

**Issue by coupej** [laravel/jetstream#1539]
### Jetstream Version

5.2

### Jetstream Stack

Livewire

### Laravel Version

11.25.0

### PHP Version

 8.2.24

### Database Driver & Version

Apple M1 14.6.1 with homebrew en Laravel Valet as hosting. composer: aliased to /Users/*****coupej/composer.phar

### Description

I tried installing jetstream and it keeps crashing silently running the line $this->requireComposerPackages('livewire/livewire:^3.0')

This resulted in a ton of weird issues like double migrations, not published views,  etc but no error was shown on the command line. It just did nothing. 

I wouldn't know why it didn't work, but it would help a ton if I had had a warning that the require didn't work instead of crashing silently. 

### Steps To Reproduce

Not quite sure what the issue was, however I do think the installation process could be made more robust by adding a warning message when requireComposerPackages returns false. I saw the the extra step was added to exit the installer when a composer require fails, but  it would be much easier to just let it finish the rest of the installation. In that case i would have noticed that the livewire require was missing and the rest of the installation would have been present. Now even if i noticed that I was in a broken state for my project.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
