### ISSUE TITLE
Installation Overwrites Users Table Migration

### ISSUE THREAD

**Issue by zachweix** [laravel/jetstream#180]
- Jetstream Version: 1.1.2
- Jetstream Stack: Inertia
- Laravel Version: 8.1.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
I just upgraded to Laravel 8 and decided to try out Jetstream, but when I ran `jetstream:install` it overwrote the create users migration. The problem with that is twofold. Firstly, I already ran that migration, so running `php artisan migrate` won't accomplish anything and also it removed changes that I made to the users table, so now I have to reimplement them.

### Steps To Reproduce:
Have a Laravel 7 projects with migrations already run.
Upgrade to Laravel 8.
Composer Install Jetstream and run `php artisan jetstream:install inertia --teams`
Look at the file database/migrations/2014_10_12_000000_create_users_table.php and see that the data was overwritten

**Comment by driesvints** [comment]
You'll need to create a new migration. Jetstream is meant to be used with new applications. We cannot know what kind of migrations or table modifications you've already done on your users table so you'll need to figure out which changes you need yourself if you want to install jetstream on an existing app.

**Comment by jdecode** [comment]
While I see the reasoning above, however (out of sheer curiosity) - what is the issue with moving the changes to a new migration rather than updating the existing users migration?

It would still work, and would also allow people to make some other changes in their application (say, a boilerplate Laravel version, before setting up Jetstream).

There should NOT be any concern with the change being requested, right?

When using Jetstream for new applications - that would continue to work.
When using Jetstream for existing applications - that would continue to work as well (at least from "migrations" POV).

It is not a change that breaks anything in Jetstream.
It is a change that definitely helps people in certain scenarios - and people can still go back to the above recommendation of "You'll need to create a new migration..."
