### ISSUE TITLE
Cannot find id of non object

### ISSUE THREAD

**Issue by rhaider-dev** [laravel/jetstream#238]
- Jetstream Version: 1.2.1
- Jetstream Stack: Livewire
- Laravel Version: 8.0.0
- PHP Version: 7.2.14
- Database Driver & Version: mysql

### Description:
Produces error when I login to dahsboard.

### Steps To Reproduce:
1. Create a user using api.
2. Login with new created user
3. Showing error of id 

When I modify user database and give a value in 'current_team_id', the error resolves.
![Capture](https://user-images.githubusercontent.com/60954367/93705598-66d5fc80-fb40-11ea-812a-d85e491cdfab.PNG)

**Comment by howlowck** [comment]
I ran into the same issue.

Here are my repro steps:
1. Cloned the latest Laravel
2. Installed Jetstream by running `artisan jetstream:install inertia --teams` 
3. Registered a user
4. uncommented `Features::teams(),` in `config/jetstream.php`

The issue is for some reason the install script didn't copy the correct stub over to `app/Actions/Fortify/CreateNewUser.php`.
It should have copied the [CreateNewUserWithTeams](https://github.com/laravel/jetstream/blob/1.x/stubs/app/Actions/Fortify/CreateNewUserWithTeams.php) stub overwriting the previous stub, but didn't.

Anyway, **TL/DR, you can do the following to fix the issue**:
1. Delete the existing user (optional)
2. Copy the content of [the CreateNewUserWithTeams stub](https://github.com/laravel/jetstream/blob/1.x/stubs/app/Actions/Fortify/CreateNewUserWithTeams.php) into your `app/Actions/Fortify/CreateNewUser.php`
3. create a new user
4. log in with the new user

Hope this helps.

It's weird that it does seems like some of the operations like [Line 399 in the InstallCommand](https://github.com/laravel/jetstream/blob/1a05aba0ab57b072c1698798530652a7a04cb0d9/src/Console/InstallCommand.php#L399) didn't work, since I had to uncomment the line out myself, but other copy operations did work (besides [Line 422](https://github.com/laravel/jetstream/blob/1a05aba0ab57b072c1698798530652a7a04cb0d9/src/Console/InstallCommand.php#L422).

I'm running PHP 7.4

**Comment by driesvints** [comment]
> Create a user using api.

@rhaider-dev please explain how you did this.

@howlowck you need to use the Laravel installer to properly run the install procedure, not just clone the skeleton.

**Comment by driesvints** [comment]
@rhaider-dev I'm thinking you only created a user record and not a personal team for a user. Each user needs a personal team record that's linked to the user.

**Comment by driesvints** [comment]
Also see: https://jetstream.laravel.com/1.x/features/teams.html

> By default, every registered user will belong to a "Personal" team.
