### ISSUE TITLE
Inertia Sharing and Versioning

### ISSUE THREAD

**Issue by devingray** [laravel/jetstream#326]
Hi @taylorotwell and the Laravel Team. 

I am wondering if a PR to allow Inertia versioning and sharing to be published would be something that the package would be interested in. 

Some context:

Versioning: 
Currently because Jetstream does not version the Inertia Bundle it needs a cleared cache reload before seeing changes on the front end. 

This can be easily achieved in the register method of `AppServiceProvider.php` but I personally like to create an InertiaServiceProvider to keep everything in their neat little rows. 

An example code would be something like 

```php
            Inertia::version(function () {
                return md5_file(public_path('mix-manifest.json'));
            });
```

Sharing

I noticed that sharing is provided at a middleware level but is not published, this houses some data such as has_two_factor enabled, I guess it could be overwritten if I were to create my own but this just adds steps to the request cycle.

My idea is to create an InertiaServiceProvider with some default boilerplate to get this going. 

Feel free to close if this is not the direction of the package

**Comment by claudiodekker** [comment]
Saw this requested on Twitter as well, and I think it'd be a great addition:
- Laravel uses Laravel Mix to generate the `mix-manifest.json` out of the box
- In my experience working on Inertia with @reinink, it's very rare that people don't want this automatic asset versioning

I was already planning on creating a PR for this later today, but since now there's a ticket for it, feel free to assign it to me @driesvints 👍

**Comment by reinink** [comment]
It's worth noting that unless you actually use `mix.version()`, this won't help. You need the two features enable for versioning to work...otherwise the md5 hash never changes.

Would adding `.version()` to the `webpack.mix.js` be too opinionated?

**Comment by driesvints** [comment]
I always add it by default myself but unsure how @taylorotwell feels about it.

**Comment by reinink** [comment]
Yeah same.

And, just to be clear, I'm only suggesting that you'd add `.version()` to the Jetstream `webpack.mix.js` stub, not the Laravel default. 👍

**Comment by driesvints** [comment]
I'd do both but that's maybe a bit too opinionated 😄

**Comment by m1guelpf** [comment]
Keep in mind that this still doesn't cover cases like Vapor where there's no mix manifest file. If this is added, I'd rather have it in userland where it can be easily removed.

**Comment by claudiodekker** [comment]
@m1guelpf Good point.

As for adding it to the `webpack.mix.js`, I considered that, but didn't do it because it's shared with Livewire. 
We could add the `.version()` to it, but then it would be automatically enabled over there as well. 
Alternatively, I can copy the `webpack.mix.js` to the Inertia-specific stubs, and only add it there.

Thoughts?

**Comment by devingray** [comment]
I have to say after having a look how I would implement this I do agree with @m1guelpf here that the versioning is perhaps not right for the vendor code. 

This should be a config the user decides to want or not want.

**Comment by taylorotwell** [comment]
This is solved in master branch.
