### ISSUE TITLE
Uncaught ReferenceError: route is not defined

### ISSUE THREAD

**Issue by TechhDan** [laravel/jetstream#482]
- Jetstream Version: 1.6.1
- Jetstream Stack: Inertia
- Laravel Version: 8.15.0
- PHP Version: 7.4.12
- Database Driver & Version: mysql v8.0.20

Description: Login page displays error on the web console. This message disappears once a user is logged in.
`Uncaught ReferenceError: route is not defined at Module../resources/js/app.js`

Steps To Reproduce:
1. laravel new sample
2. composer require laravel/jetstream
3. php artisan jetstream:install inertia (or with --teams)
4. npm install && npm run dev
5. php artisan migrate
6. php artisan serve
7. Visit Login, Registration, or Forgot Password page to view error on console.

![UncaughtReferenceErrorRoute](https://user-images.githubusercontent.com/11691784/99823456-69de7080-2b22-11eb-9e27-7a17c5b953a5.png)

**Comment by driesvints** [comment]
What version of laravel-jetstream in your package.json are you using?

**Comment by TechhDan** [comment]
I'm using laravel-jetstream version 0.0.3

**Comment by andreliem** [comment]
Having same issue as well, same versions.

**Comment by andreliem** [comment]
But I don't have the issue on another app with a older version

```
  "inertiajs/inertia-laravel": "^0.2.4",
  "laravel/jetstream": "^1.5",
```

```
    "laravel-jetstream": "^0.0.3",
```

**Comment by philmmoore** [comment]
I had this issue myself when installing Jetstream with Inertia for the first time where there were a few hiccups along the way  i.e. the installer didn't work as expected because of my local environment so I had to install a few dependencies manually.

For me once I'd created an account and was taken to /dashboard the issue was clearer since I could only see @routes output in the browser. This is because the @routes blade directive wasn't available from the `tightenco/ziggy` and should've been added by the installer (but it wasn't because of those hiccups) https://github.com/laravel/jetstream/blob/daba98419164024e2c071f5547dd5569aba69d98/src/Console/InstallCommand.php#L249

If that's the same for you just do `composer require tightenco/ziggy` and it should resolve your issue.

**Comment by rokde** [comment]
And the calls to `route('logout').url()` are wrong. There is no object you can call `.url()` at. Just remove and you are fine. It is in multiple Stub Templates in Jetstream wrong. So replace all occurrences to get it back to work.

**Comment by TechhDan** [comment]
The Laravel Jetstream login, two-factor login, registration, password reset, and email verification views have guest.blade.php as the base layout while everything else uses app.blade.php. In the guest.blade.php the @routes directive is missing but the mix('js/app.js') depends on it. I tried adding it to the guest.blade.php template but now i get a `TypeError`
![MissingRoutesDirective](https://user-images.githubusercontent.com/11691784/99882434-716b4b80-2bee-11eb-977d-6fe040701ebc.png)
![CannotReadPropertyOfNull](https://user-images.githubusercontent.com/11691784/99882433-716b4b80-2bee-11eb-9adf-acccaf267e88.png)

**Comment by dinoluck** [comment]
I'm getting the route is not defined on a fresh install of Laravel/Jetstream/Inertia/Vue stack when I go to /login

**Comment by bricehartmann** [comment]
On a fresh install I removed the following from `resources/views/layouts/guest.blade.php`
```
<!-- Scripts -->
<script src="{{ mix('js/app.js') }}" defer></script>
```
If I understand correctly, because all the Jetstream auth scaffolding is in blade (with livewire I think?), the application scripts are not necessary for guest views.

This resolved the error but I'm eager to learn about any other solution someone may have, I'm not sure if the application scripts _should_ be included in guest views or not.

**Comment by nbs** [comment]
I had all the same problems described above on a fresh installation.

I was able to fix it but changing the branch to "master" in composer.json.

"laravel/jetstream": "master",

And repeating the same steps. The 1.6 release seems broken.

**Comment by driesvints** [comment]
Managed to reproduce this. Investigating.

**Comment by driesvints** [comment]
This should fix it: https://github.com/laravel/jetstream/pull/485

**Comment by TechhDan** [comment]
> This should fix it: #485

Thank you!

**Comment by phoenixg** [comment]
I meet the same issue, wonder how fix?

**Comment by tamodaleko** [comment]
@phoenixg Try running npm run production
