### ISSUE TITLE
Login modal doesn't close if used to reauth after session timeout

### ISSUE THREAD

**Issue by aligajani** [laravel/jetstream#565]
- Jetstream Version: Latest
- Jetstream Stack: Latest
- Laravel Version: Latest
- PHP Version: 7.2
- Database Driver & Version: N/A

### Description:

![image](https://user-images.githubusercontent.com/1730778/103156867-23c1a000-47a5-11eb-84b9-ac6aef58625d.png)

### Steps To Reproduce:

Login into a fresh installation of Jetstream. Don't click Remember me. Now go to anypage like profile. Purge the Session keys from cookies and refresh page. A login modal will show up asking you to reauth. When you succesfully reauth, a new session opens up in the modal, but the modal remains on top of the old session, creating a duplicate UI. The intended behaviour I think is for the reauth modal to close upon succesfull reauth.

**Comment by driesvints** [comment]
Hi there, please don't post an issue without filling out the versions in the issue template. It's there for a reason.

The above has been fixed in v2 and will be available in the next major release. This issue has been posted quite a bit already so please make sure to search the issue tracker before opening a new one. Thanks.

**Comment by ArielMejiaDev** [comment]
## This is the expected behavior of InertiaJS

The idea is to get that modal to get errors or dump data on development mode.

You can set your app environment on production and follow the InertiaJS documentation on [error handling](https://inertiajs.com/error-handling) and create custom messages and custom Vue component, with that changes the modal would be swap for your custom error component.

Or you can solve it easy with a package that I created [Inertia error page](https://packagist.org/packages/arielmejiadev/inertiajs-error-page) for this exactly behavior.

Just follow the readme and you would get the behavior as we all expect and additionally it adds a beautiful error screen designed by Steve Schoeger for Laravel 5.7, but updated with TailwindCSS classes
