### ISSUE TITLE
Route::livewire() not work 

### ISSUE THREAD

**Issue by adrian-ub** [laravel/jetstream#57]
- Jetstream Version: v0.6.4
- Laravel Version: ^8.0
- PHP Version: 7.4.10
- Database Driver & Version: Mysql

### Description:
Route::livewire() not work on routes/web.php

```
Route::livewire('/', 'pages.home')->name('home');
```

### Steps To Reproduce:
``` 
laravel new app --jet --dev

Livewire

php artisan make:livewire pages.home

edit routes/web.php

Route::livewire('/', 'pages.home')->name('home');
```

![image](https://user-images.githubusercontent.com/22903142/92292656-f98d5f00-eee3-11ea-8cf5-5afa49d8a1f2.png)

**Comment by adrian-ub** [comment]
Sorry, I already found the correct way in the new version, in case it helps someone, they should change the line
```
 Route::livewire('/', 'pages.home')->name('home');
```
to
```
Route::get('/', [Home::class,'render']);
```

**Comment by jessarcher** [comment]
> ```
> Route::get('/', [Home::class,'render']);
> ```

This isn't really equivalent to `Route::livewire()` because it doesn't automatically wrap the component in the app layout.

I'm new to Livewire, but [the docs](https://laravel-livewire.com/docs/rendering-components#route-registration) say that's how it's supposed to work so it seems like there is still something wrong here.

Where did you find this documented as the "correct way in the new version"? Is it a Livewire 2.0 thing?

**Comment by adrian-ub** [comment]
Check the Jetstream code to see what the livewire components called, I also found this documentation on livewire for version 2 [https://github.com/livewire/livewire/issues/1429](https://github.com/livewire/livewire/issues/1429)

**Comment by TrentDPT** [comment]
My jetstream does not seem to recognize the "class" when I use that format?  What else did you do to get this to work?  Why would i get an error that says...

Target class [Home] does not exist.

**Comment by adrian-ub** [comment]
@TrentDPT Did you import yet?

example:

```
// route/web.php

use App\Http\Controllers\Pages\HomePage;

Route::get('/', HomePage::class)->name('home');

```
