### ISSUE TITLE
User route config

### ISSUE THREAD

**Issue by c-fitzmaurice** [laravel/jetstream#572]
In the Jetstream config file there is no way to adjust the routes, like the Fortify config file. It would be great if we could customize the user profile URLs. I would like to use my User Model's `username` field as a slug for the user profile:

from
```
/user/profile
```
to
```
/{username}/profile
```

IIf this is something that would be considered useful I could maybe start looking into a PR.

**Comment by joelbutcher** [comment]
Whilst I agree route customisation would be nice, I'm not sure your example fit your desired outcome. 

Fortify allows you to specify a route _prefix_ to **all** routes. 

Let's take your example:

```
{username}/profile
```

In order to make this possible, you would either need to always assume that the `username` wildcard will resolve for the current user. I'm personally not a fan of this as I've always gone down the route that assumptions are bad in programming. This would also mean that routes such as `foo/profile` would pass and allow you to view the your profile (given the current controller logic). I suspect this isn't the effect you're looking for?

One alternative is to change the logic used to resolve the user and use the `username` route wildcard. The complexity here is that a `User` policy will need to be implemented as well as "view" routes so that when visiting a users profile that is not your own, you do not end up updating or _deleting_ their account. I suspect this kind of change is unlikely to get Taylor's approval due to the maintenance burden associated with the complexity. 

The final alternative is to publish the routes file using

```
php artisan vendor:publish --provider="\Laravel\Jetstream\JetstreamServiceProvider" --tag=jetstream-routes
```

Then modifying your `RouteServiceProvider` to load the routes from the published `routes/jetstream.php` file.

**Comment by driesvints** [comment]
@c-fitzmaurice Please see the answer above.

@joelbutcher thanks!

**Comment by c-fitzmaurice** [comment]
Thanks @joelbutcher !
