### ISSUE TITLE
Problem when installing Livewire on Jetstream

### ISSUE THREAD

**Issue by AbeGNING** [laravel/jetstream#61]
- Jetstream Version: 0.6.4
- Laravel Version: 8.0
- PHP Version: 7.4.9

### Description:
I'm new to Jetstream, but I get the same error after trying to install it several times.

### Steps To Reproduce:
1. I installed Laravel 8 with laravel new project --dev.
2. then Jetstream with composer require laravel/jetstream.
3. Livewire installation: php artisan jetstream: install livewire
4. Compiling the frontend assets: npm install && npm run dev
5. I encounter the error when I do: php artisan serve or php artisan vendor: publish --tag = jetstream-views

![Capture](https://user-images.githubusercontent.com/50240072/92305648-bd580e00-ef78-11ea-9fa8-6b75207cd834.PNG)

**Comment by calebporzio** [comment]
Hi @AbeGNING,

I was unable to reproduce your error. I followed the steps exactly and everything worked perfectly for me.

My best guess as to what is going on:
* The `::macro` method was PR'd into that class 2 months ago (to 7.x AND master (8.x)): https://github.com/laravel/framework/pull/33354
* Therefore, my only guess is that you are using a version of Laravel before that PR made it in. This is odd because you explicitly newed up a Laravel app with `--dev.

One thing you could try is running: `composer global update "laravel/installer:^4.0"` (If that doesn't work, manually bump your ~/.composer/composer.json file's `laravel/installer` version to "^4.0").

Hope one of these things helps!

**Comment by edgrosvenor** [comment]
--dev was giving me an old version of Laravel last night too. So this might be composer's fault somehow. I don't know enough about its inner workings to assign blame, but I definitely witnessed some misbehavior.

**Comment by ClementN** [comment]
I was experiencing the exact same problems. 
```composer global update "laravel/installer:^4.0"``` did not fix it as the installer was not updated on 4.0 

but

manually bumping the ```~/.composer/composer.json``` file's laravel/installer version to "^4.0", followed by installer update, **fixed the problems**.

Thank you.
