### ISSUE TITLE
publish Http\Livewire

### ISSUE THREAD

**Issue by jpkontreras** [laravel/jetstream#87]
please

**Comment by calebporzio** [comment]
@jpkontreras, please expound on the reasons you would want this published.

What specific customizations are you looking for?

I don't have control over this package, but I am both curious, AND want your issue to be a good place to have this discussion.

**Comment by ClementN** [comment]
Hello @calebporzio . 

Here is what I would customize in ```Http/Livewire``` if it were accessible to me:

1. I will add custom fields for Team model in ```vendor/laravel/jetstream/src/Http/Livewire/UpdateTeamNameForm.php```
as discussed in this PR https://github.com/laravel/jetstream/pull/72 
(thank you for your solutions)

1. I will apply the same approach in ```vendor/laravel/jetstream/src/Http/Livewire/UpdateProfileInformationForm.php``` 
As commented in the PR above https://github.com/laravel/jetstream/pull/72#issuecomment-688031411 , this file currently add the entire User info ```toArray()```

1. I will add some custom ```$this->emit('teamUpdated');``` that I need to use in some sibling components. 

This is because I show the current team name in the header (livewire component) for easier orientation of the user and I need that component to refresh when the name of the current team is updated.

**Comment by ClementN** [comment]
And one more that I would do is to implement **real-time validation** for some of the fields.

4. For example,  I need to have unique team names and also I need to make some verification against ```team_type``` (another custom field we have to use)

**Comment by driesvints** [comment]
This is a feature request. Feel free to attempt to PR something.

**Comment by jpkontreras** [comment]
Hi @calebporzio
Answering to your question, nothing in particular i want to see the implementation and update if i need it.
Also i believe that if there is a piece that is being published(views) why the others are not?. 

Greetings
