### ISSUE TITLE
Error after LOG OUT OTHER BROWSER SESSIONS

### ISSUE THREAD

**Issue by misenhei** [laravel/jetstream#985]
- Jetstream Version: 2.6.7
- Jetstream Stack: Livewire
- Uses Teams: no
- Laravel Version: 9.2.0
- PHP Version: 8.1.3
- Database Driver & Version:  10.6.7-MariaDB - MariaDB Server 
- 
### Description:
After executing "LOG OUT OTHER BROWSER SESSIONS" successfully anything else attempted, such as clicking SAVE for profile information, on the profile page will result in an "Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data." If you attempt to refresh the page or go to another, say Dashboard, you are required to log back in.

### Steps To Reproduce:
Install Laravel 9 and Jetstream with Livewire
Register a new user
Login user
Go to /user/profile
Click "LOG OUT OTHER BROWSER SESSIONS"
Enter user password and click "LOG OUT OTHER BROWSER SESSIONS"
The Done notification will show.
Click SAVE on Profile information.
If browser developer tools are open you will see in the console: "Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data."
SAVE button will remain grayed out.
Click Dashboard and you will be requested to log back in.

**Comment by driesvints** [comment]
There's a few things happening when I login to chrome and safari at the same time:

- You're not only logged out from other session but from your current session as well (causing the issue reported)
- Your session DB records remain but your main session's record user_id is set to null which is odd...
- As soon as you login again both sessions still appear
- If I refresh the safari session, the user_id is unset instead of the DB record being removed

I've been investigating this now for a bit and still am clueless why the DB records aren't permanently removed or why the current session is removed as well...

**Comment by ChrisRiddell** [comment]
Played around with this for an hour and have narrowed the issue down to this line

https://github.com/laravel/jetstream/blob/333aeaad352987a53524bb6d83a484e101ca0612/src/Http/Livewire/LogoutOtherBrowserSessionsForm.php#L60

if you comment it out it works as expected. trying to dig into why I got confused with the whole contracts stateful guard and where that logoutOtherDevices() is in the framework.

I did try to replace it with `Auth::logoutOtherDevices($this->password);` from https://laravel.com/docs/9.x/authentication#invalidating-sessions-on-other-devices
but it errors out saying `Method Illuminate\Auth\RequestGuard::logoutOtherDevices does not exist.`

**Comment by nausixkiz** [comment]
Same question .. My session always changes every refresh / request

**Comment by driesvints** [comment]
Please only comment if you have something to add to the discussion. Use upvotes to indicate you're also experiencing this issue.

**Comment by taylorotwell** [comment]
Fixed by https://github.com/laravel/framework/commit/50b46db563e11ba52a53e3046c23e92878aed395
