### ISSUE TITLE
email verification: invalid Signature with URL::forceScheme("https")

### ISSUE THREAD

**Issue by simonbuehler** [laravel/jetstream#988]
- Jetstream Version: 2.6.5
- Jetstream Stack:  Livewire
- Uses Teams: no
- Laravel Version: 8
- PHP Version: 8.0
- Database Driver & Version:

### Description:

when using laravel behind a proxy or load balancer that does the ssl handling and laravel runs on plain http with using 
`URL::forceScheme` to use https for the resulting routes, email verification fails with `403 Invalid Signature`

### Steps To Reproduce:
use laravel on http and use 

```php
    public function boot()
    {
        if($this->app->environment('production') || $this->app->environment('staging')) {
            URL::forceScheme('https');
        }
    }
```
in `AppServiceProvider`

**Comment by driesvints** [comment]
This sounds like a server-level issue rather than a Laravel issue. Please use a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
