### ISSUE TITLE
Auth::login and Auth::loginUsingId causes log out

### ISSUE THREAD

**Issue by fylzero** [laravel/jetstream#997]
- Jetstream Version: 2.6.7
- Jetstream Stack: Inertia
- Uses Teams: no
- Laravel Version: 9.4.1
- PHP Version: 8.1.3
- Database Driver & Version: MySQL v8.0.28 for macos12.2 on arm64 (Homebrew)

### Description:
Auth::login and Auth::loginUsingId causes user to be logged out

### Steps To Reproduce:
- Install fresh copy of Laravel 9 w/ Jetstream + Inertia
- Create a route to switch users with Auth::login($user) or Auth::loginUsingId($id)
- Create 2 user accounts
- Log in as user 1
- Try using the route to login as user 2
- Return to the dashboard
- You are logged out instead of being logged in as the other user

https://github.com/fylzero/bug-report

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
@fylzero is this one resolved as well now?

**Comment by fylzero** [comment]
@driesvints Sorry to say, this seems to have resolved in a fresh Laravel app but not in my existing app after updating.  Apologies in advance if I am missing something obvious.

Steps I've taken:
- composer dump-autoload
- php artisan optimize:clear
- Removed `vendor` directory
- composer install
- composer update
- I'm definitely on v9.5.1 and the reversion change you all just made is there
- My linter still says getDefaultDriver is not available
- I am still getting logged out when trying to impersonate another user

**Comment by fylzero** [comment]
@driesvints Here is the repo, I've linked in the OP as well.

https://github.com/fylzero/bug-report

Instructions:
- Pull repo, setup database, migrate/fresh/seed
- There are 2 pre-seeded users w/ password set to `password`
- Login as user #1 `dries@exmaple.com`
- Go to the `/switch/2` route - this should log you in as User #2
- Return to the root url of the app - `/`
- You will be logged out instead of logged in as User #2

**Comment by fylzero** [comment]
> @fylzero Can you try reverting those changes made in 9.4.1 and see if it resolves the issue? [laravel/framework@50b46db](https://github.com/laravel/framework/commit/50b46db563e11ba52a53e3046c23e92878aed395)
> 
> Line to comment out: [404labfr/laravel-impersonate#154 (comment)](https://github.com/404labfr/laravel-impersonate/issues/154#issuecomment-1062986064)

Yes.  If I comment out `\Laravel\Jetstream\Http\Middleware\AuthenticateSession::class` from `app/Http/Kernel.php` I do not get logged out.

**Comment by fylzero** [comment]
@driesvints I have verified that when trying to use this functionality the evaluations for `$request->session()->get('password_hash_'.$this->auth->getDefaultDriver())` and `$request->user()->getAuthPassword()` are not equal to each other and this is causing the system to log the user out.

See:  `vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php:55`

**Comment by fylzero** [comment]
@driesvints You are correct.  Yes, commenting this out in the Foundation Kernel also resolves the logout issue.

**Comment by fylzero** [comment]
@driesvints It appears in Jetstream this is trying to compare the password_hash_sanctum to the password_hash_web tokens.

**Comment by fylzero** [comment]
@driesvints I read the changelog in Laravel and yes reverting the change here:  https://github.com/laravel/framework/commit/50b46db563e11ba52a53e3046c23e92878aed395

...also resolved the issue.  I believe that is the problem.

**Comment by taylorotwell** [comment]
I can't recreate this.

**Comment by taylorotwell** [comment]
@fylzero what you are reporting in your example repo is NOT a bug. That is in fact PROVING that session authentication is working correctly. You used `login` but didn't update the flashed password in the session that authenticate session uses to compare the current user's password to the one in the session - thus, you are logged out. 

I can't recreate it when using the impersonation package in question because they fully flush the session by logging out and then logging in again.

<img width="542" alt="CleanShot 2022-03-15 at 16 21 22@2x" src="https://user-images.githubusercontent.com/463230/158474681-d8bab631-ea52-4866-9fa2-3936430af05d.png">

This works on Jetstream using the lab404/laravel-impersonate package.

**Comment by fylzero** [comment]
@taylorotwell Fair enough.  This was working before that update so, wasn't sure.  I'll look at what the package is doing and make the necessary changes.  Obviously this only "broke" user impersonation so, not super mission-critical.

Thanks for providing this info!

**Comment by taylorotwell** [comment]
Yeah - it's a bit complicated. It helps if you have a good grasp of how authenticated sessions work. I'll try to summarize:

When using authenticated sessions...

- We store the current user's hashed password in the session...
- On each request, we compare the user's hashed password from the database against the hashed password in the session
- If they do not match, log the user out

So, with this in place, when a user updates their password in a user profile section of an application, all other sessions for that user will be logged out because their copy of the password in their sessions no longer matches the database.

So, back to your example, you log a new user into the application, but you never update the session password hash accordingly. Therefore, they no longer match and you are logged out.

**Comment by fylzero** [comment]
For anyone else running into what I did, this seems to work for me but definitely feels backwards / like I'm cheating.  getAuthPassword() seems to be grabbing the `password_hash_web` from session and I'm just forcing the sanctum token to match that to hack through things.  I could be wrong, but it would be nice to do this the other way around imo.  I also couldn't figure out how to dynamically grab the session key variable how `vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php` does.  I may keep working on this later...  but this does solve my problem for now.

```
// Log in as impersonated user
$user = Auth::loginUsingId($userId);

// Store impersonated user's password hash in session
session(['password_hash_sanctum' => $user->getAuthPassword()]);
```

**Comment by larskoole** [comment]
The simplest solution is to put `auth()->shouldUse('web');` above any `auth()->login()` or `auth()->logout()` in your controller. No need for setting the new password hash.

I don't know if this brings any security risks though.
